import { useCallback, useEffect, useRef, useState } from 'react';
import type { Model, SimResult } from '../model';
// Generated by `wasm-pack build crates/wasm --target web --out-dir ../../web/src/wasm`.
// Run `pnpm build:wasm` before `vite` (the dev/build scripts already do this). Until
// then this import (and its types) won't resolve — that's expected.
import init, { simulate as wasmSimulate } from '../wasm/ninety_ci_wasm';

// Bucket size handed to the engine.
//
// KNOWN ISSUE: the engine treats `step` as an ABSOLUTE bucket width, so the number
// of histogram buckets is roughly (output range / step). For large-magnitude
// outputs (e.g. ~200,000) a small step like 0.1 would allocate millions of buckets.
// 1.0 is a safe placeholder for small models; before shipping, scale this to the
// output magnitude (or add a UI control / let the engine pick). See
// DOCS/architecture/wasm-module.md.
const DEFAULT_STEP = 1;

interface VarPayload {
  name: string;
  shape: string;
  lower: number;
  upper: number;
}

interface RawResult {
  ci_low: number;
  ci_high: number;
  buckets: number[];
  counts: number[];
  samples: number;
}

export function useNinetyCi() {
  const ready = useRef<Promise<unknown> | null>(null);
  const [running, setRunning] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const ensureReady = useCallback(() => {
    if (!ready.current) ready.current = init();
    return ready.current;
  }, []);

  // Kick off module initialization on mount so the first Run is fast.
  useEffect(() => {
    ensureReady();
  }, [ensureReady]);

  const run = useCallback(
    async (model: Model): Promise<SimResult> => {
      setRunning(true);
      setError(null);
      try {
        await ensureReady();
        const vars: VarPayload[] = model.variables.map((v) => ({
          name: v.name,
          shape: v.shape,
          lower: v.p5,
          upper: v.p95,
        }));
        const raw = wasmSimulate(model.equation, vars, model.samples, DEFAULT_STEP) as RawResult;
        return {
          ciLow: raw.ci_low,
          ciHigh: raw.ci_high,
          buckets: raw.buckets,
          counts: raw.counts,
          samples: raw.samples,
        };
      } catch (e) {
        const msg = e instanceof Error ? e.message : String(e);
        setError(msg);
        throw e;
      } finally {
        setRunning(false);
      }
    },
    [ensureReady],
  );

  return { run, running, error };
}
